### PR TITLE
Add a sink “test” page with all elements

### PR DESCRIPTION
**Pull request by platosha**
Connected to vaadin/components-team-tasks#319

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-material-theme/31)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/sink.html, line 118 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/31#-L6WS20CbcMXaG-9BE0e:-L6WS20CbcMXaG-9BE0f:bn6h2vu) ([raw file](https://github.com/vaadin/vaadin-material-theme/blob/7c4560cbab6be8a82e09c1a646a0c1f4f3462c4f/test/sink.html#L118)):*
> ```HTML
>                 <template>
>                   <custom-style>
>                     <style include="lumo-typography lumo-color">
> ```

these style modules should be changed

---

*[test/sink.html, line 150 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/31#-L6WSjx01H_oxeTqggkA:-L6WSjx01H_oxeTqggkB:bc5s1j7) ([raw file](https://github.com/vaadin/vaadin-material-theme/blob/7c4560cbab6be8a82e09c1a646a0c1f4f3462c4f/test/sink.html#L150)):*
> ```HTML
>               <vaadin-item disabled><iron-icon icon="icons:file-upload" class="small-icon"></iron-icon> Option four</vaadin-item>
>             </vaadin-list-box>
>             <h6>Lumo icons</h6>
> ```

Lumo should be also renamed here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/31)*

**Comment by platosha** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/sink.html, line 118 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/31#-L6WS20CbcMXaG-9BE0e:-L6au5GXClxLlXcuuGvp:b-896fix) ([raw file](https://github.com/vaadin/vaadin-material-theme/blob/7c4560cbab6be8a82e09c1a646a0c1f4f3462c4f/test/sink.html#L118)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

these style modules should be changed
</blockquote></details>

Done.

---

*[test/sink.html, line 150 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/31#-L6WSjx01H_oxeTqggkA:-L6au69wc6dBnd-H3Nq4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-material-theme/blob/7c4560cbab6be8a82e09c1a646a0c1f4f3462c4f/test/sink.html#L150)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Lumo should be also renamed here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/31)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/31)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/31#-:-L6b3GWHqD_XKWAxLVYm:bnfp4nl)*

**Pull request merged**
