### PR TITLE
Material theme for Radio button

### PR DESCRIPTION
**Pull request by h00k00**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-material-theme/21)

### CODE REVIEW

**Comment by platosha** [comment]
[Material guideline](https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-baseline-grids) says: “All components align to an 8dp square baseline grid for mobile, tablet, and desktop. Iconography in toolbars align to a 4dp square baseline grid.”

The resulting component height of 29.2667px, as seen on the demo page, is not aligned with the 8dp baseline grid:


Affects single radio button height in vertical groups too:


---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/21#-L1wHth9rYw6gRTEHQZP:-L1wHth9rYw6gRTEHQZQ:b-cxwl8) (no related file):*
:thinking: 

[Material Design Guidelines](https://material.io/guidelines/components/selection-controls.html#selection-controls-radio-button) specify much bigger ripple:


`<paper-radio-button>`’s ripple feels pretty big too:


The ripple of the [Radio Button from Material Components for the Web](https://material-components-web.appspot.com/radio.html) is outstandingly huge:


Compared, the ripple of material `<vaadin-radio-button>` is quite small.

Additionally, the implementations above show ripple on every click, on only when the button is activated.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/21#-L1wIqL_a1nk7RRXEh8A:-L1wIqL_a1nk7RRXEh8B:b-41fkq4) (no related file):*
The focus ring style looks broken, dirty dark and blurred:


Compare to the subtle and clean focused style from the Guideline:


---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/21#-L1wKFlkxx0ZE6k6OVY-:-L1wKFlkxx0ZE6k6OVY0:b-co9dty) (no related file):*
The focus ring style visually cuts the button above:





---

*[vaadin-radio-button.html, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/21#-L1w2RXvGu-Vh5SHqLSJ:-L1w2RXvGu-Vh5SHqLSK:b-c7l9rz) ([raw file](https://github.com/vaadin/vaadin-material-theme/blob/509ae694bc9085de459bef2f3e587f6732c1d816/vaadin-radio-button.html#L16)):*
> ```HTML
>       }
> 
>       [part="wrapper"] {
> ```

`<vaadin-radio-button>` does not seem to have a `part="wrapper"` in the template: https://github.com/vaadin/vaadin-radio-button/blob/d462d15aaa06d14f21425f07e3a1d20a5b923033/src/vaadin-radio-button.html#L47-L60

Or am I missing something?

---

*[vaadin-radio-button.html, line 180 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/21#-L1wKpvQ8B4gaGutXaSL:-L1wKpvQ8B4gaGutXaSM:b-4yundq) ([raw file](https://github.com/vaadin/vaadin-material-theme/blob/509ae694bc9085de459bef2f3e587f6732c1d816/vaadin-radio-button.html#L180)):*
> ```HTML
> 
> 
> <dom-module id="material-radio-group" theme-for="vaadin-radio-group">
> ```

`<vaadin-radio-group>` is a separate element. Hence, it’s expected to have a dedicated theme file `vaadin-radio-group.html`.

This is also important to make Material aligned with how Valo theme files are structured at the moment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/21#-:-L1w9Cv7LJdWjlS0Uwf_:b-ik1606)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/21)*

**Comment by platosha** [comment]
Expected for click animation:
- Radio button’s circle does not move
- Ripple is triggered on every click
paper-radio-button-click
material-components-radio-click

Actual click animation:
- Radio button’s circle scales while mouse is down
- Only activating click triggers the ripple
material-vaadin-radio-button-click

---

One more small, but still noticable thing with `focus-ring` style, when <kbd>Tab</kbd> keyboard focus is gained.

Expected: the inner background color is the same as the focus-ring around, and changes immediately with focus-ring.

Actual: the inner circle background color is animated, while focus-ring is shown immediately.

Look closely inside the radio circle to notice:

material-vaadin-radio-button-inner-blink

**Comment by tomivirkki** [comment]
Merged in https://github.com/vaadin/vaadin-material-theme/commit/fb32651e6ed5c545ac833597c860cf91a27c8e61

**Pull request closed without merging**
