### PR TITLE
Material theme progress bars

### PR DESCRIPTION
**Pull request by h00k00**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-material-theme/23)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Looks like the current appearance and implementation is equal to that of Valo's (instead of https://material.io/guidelines/components/progress-activity.html#progress-activity-types-of-indicators)

**Comment by platosha** [comment]
Expected: sharp corners by default, as seen in [the Guideline’s Example](https://material.io/guidelines/components/progress-activity.html#progress-activity-types-of-indicators), [Linear Progress](https://material-components-web.appspot.com/linear-progress.html) from Material Components for the Web, and [`<paper-progress>`](https://www.webcomponents.org/element/PolymerElements/paper-progress/demo/demo/index.html).

Actual: rounded corners.
screen shot 2018-01-11 at 16 41 32

**Comment by tomivirkki** [comment]
screenshot 2018-01-11 16 57 27

Noticed this issue with increasing the element height. The inner bar doesn't heighten with the element.

**Comment by platosha** [comment]
The indeterminate animation looks still a bit not quite like in the references.

If you look closely, you can notice that the filler bar moves faster in the middle, and slower while appearing/disappearing.

Another thing is, the Material Design’s indeterminate progress animation is more complex: the filler bar there is split on two parts, and the splitter is also animated, while in this PR there is a single-part filler bar with constant width. Compare with the [slow indeterminate example of `<paper-progress>`](https://www.webcomponents.org/element/PolymerElements/paper-progress/demo/demo/index.html) (second code snippet).

I don’t know if these issues are critical or not, so let’s ask from @jouni. How close the indeterminate animation should be to the references from Material Design?

**Comment by jouni** [comment]
I agree that it’s not as good as it could be. But, I would say we have “bigger fish to fry”, and we can accept the current indeterminate progress bar as a decent starting point.

Let’s just document this in an issue and come back to it later. Maybe even add a “help wanted” label so that the community knows they can help (this could be an easy task for some CSS wizard out there)?

What I do want us to fix before merging is the border-radius on the bars, though.

So, @platosha, I’m okay merging this (after the border-radius is removed) – just make sure you create a new issue about the indeterminate style when you merge the PR.

**Comment by tomivirkki** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/23)*

**Pull request merged**
