### PR TITLE
Material theme tabs

### PR DESCRIPTION
**Pull request by h00k00**
Note: Using valo-icons still instead of material icons. Icons will be updated later

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-material-theme/22)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/22#-L1wZA3mG665XWdz0BiN:-L1wZA3n-xt6XbHKQsn0:b-d17j1z) (no related file):*
Focus style in Tabs of Material Components for the Web highlights the tab background for hover and focus styles, and this [feels very nice](http://material-components-web.appspot.com/tabs.html#one)


Right now, I can hardly see when a tab is focused. The same issue exists with `<paper-tabs>`. `<paper-tabs>` do not have background highlight on hover and focus.

The Guideline does not specify explicitly how tab focus and hover look too, unfortunately.

Not a part of the scope maybe, so this is not a blocker issue. Just an enhancement idea. IMO, would be nice to have hover and focus highlight the way Material Components Tabs have them.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/22#-L1wa8WjAWKwyxGItF9l:-L1wa8WkOzEDEwKbXiNO:b3dwup6) (no related file):*
Ripple on the underline does not feel right. Instead, the tab background should have a ripple visual click feedback, not the underline.

The Guidelines examples, `<paper-tabs>`, Tabs from Material Components, all of them visually highlight the tab background in response to the tab click, the underline just changes its position.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/22#-L1wbMu_lGObRc2T3K02:-L1wbMu_lGObRc2T3K03:b-z2pb7m) (no related file):*
Expected: wrapped tab text is centered in the tab


Actual: wrapped tab text is aligned to the left


---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/22#-L1wcA1hYg0vGgWjWCLz:-L1wcA1hYg0vGgWjWCM-:b7azjq7) (no related file):*
Expected: non-scrollable tabs are either stretched to viewport or aligned to the center:





Actual: `<vaadin-tabs>` are always left aligned:


In fact, [the Guideline](https://material.io/guidelines/components/tabs.html#tabs-specs) specifically defines two distinct types of tabs: fixed tabs and scrollable tabs. We could have one type as default behavior, and another as a theme variation.

Since it’s not expected to adjust theme to enable scrolling, I would suggest that “scrollable” is a default look, and there is also an opt-in `theme="fixed"` variation improving the look when scrolling is unnecessary.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/22#-L1wfDaiVFZSlz684dOl:-L1wfDaiVFZSlz684dOm:bvq7vse) (no related file):*
Expected: when scrolling buttons are not in use, the first tab starts exactly where the tab container starts, and there is no gap between. If the tab container has a background, the first tab touches the left side of the container:





Actual: there is a gap between the tabs container edge and the first tab edge:


---

*[vaadin-tab.html, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/22#-L1wgzxzpyvxuqR1zYQn:-L1wgzxzpyvxuqR1zYQo:bco07r2) ([raw file](https://github.com/vaadin/vaadin-material-theme/blob/1db81cba3dc868d62c4f5bacd6fb2cd1e7b5d9cc/vaadin-tab.html#L16)):*
Does not match how [The Guideline](https://material.io/guidelines/components/tabs.html#tabs-specs) specifies min and max width:

>  Width minimum and maximum (inclusive of padding)
>    Maximum: 264dp
>    Minimum: 160dp for larger views, 72 dp for smaller views

---

*[vaadin-tabs.html, line 135 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/22#-L1wix2Ux-jHNIh6cW_l:-L1wix2Ux-jHNIh6cW_m:bxt1vwa) ([raw file](https://github.com/vaadin/vaadin-material-theme/blob/1db81cba3dc868d62c4f5bacd6fb2cd1e7b5d9cc/vaadin-tabs.html#L135)):*
> ```HTML
>       }
> 
>       /* Pill theme */
> ```

Missing demo for the `pill` theme variation? I cannot find it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/22)*

**Comment by platosha** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/22)*

**Comment by web-padawan** [comment]
Review status: 3 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[vaadin-tabs.html, line 91 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/22#-L4553LZkgSnPyxmG8Fi:-L4553LZkgSnPyxmG8Fj:bgjhxzi) ([raw file](https://github.com/vaadin/vaadin-material-theme/blob/56f3d746fc770bd4c24e368ca93a7da192e968b6/vaadin-tabs.html#L91)):*
> ```HTML
>         --_material-tabs-overflow-mask-image: none;
>         -webkit-mask-image: var(--_material-tabs-overflow-mask-image);
>         mask-image: var(--_material-tabs-overflow-mask-image);
> ```

Need to wrap this property (currently supported without prefix by Firefox only) into the condition to prevent Edge crash. Example: https://github.com/vaadin/vaadin-tabs/blob/master/theme/lumo/vaadin-tabs.html#L81

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-material-theme/22)*

**Comment by tomivirkki** [comment]
Merged in https://github.com/vaadin/vaadin-material-theme/commit/02c83210c0dda538b4db0f10811b021ce6807a79

**Pull request closed without merging**
